### ISSUE TITLE
Log file shows sync tries to add repository that already exists

### ISSUE THREAD

**Issue by lboynton** [OpsLevel/kubectl-opslevel#286] opened 2024-03-21 15:06 UTC
Version: v2024.3.18

After updating to this version, we are no longer losing data :) However I've noticed the log contains this error:

```
2:49PM ERR [label-controller] Failed assigning repository '{"service":null,"repository":{"alias":"github.com:xxx/repo-name"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.
```

It looks like it's trying to set a repo when it doesn't need to?

Config is similar to the following:

```
version: "1.3.0"
service:
  import:
    - selector:
        apiVersion: apps/v1
        kind: Deployment
        excludes:
          - .metadata.namespace == "kube-system"
      opslevel:
        name: .metadata.name
        aliases:
          - '"k8s:\(.metadata.name)-\(.metadata.namespace)"'
        tags:
          assign:
            - '{"imported": "kubectl-opslevel"}'
          create:
            - '{"environment": "${environment}"}'
        repositories:
          - 'if .metadata.annotations.repository_url" then .metadata.annotations.repository_url | gsub("^git@" ; .value) | gsub ("\.git$" ; .value) else null end'
```

**Comment by taimoorgit** [comment] 2024-03-21 16:27
@lboynton Thanks for reporting this. 

Looks like this bug predates `v2024.3.18` since I was able to reproduce it on `v2024.3.4`. 

The check we do before submitting a repository update is lacklustre, it is not checking for existing repositories on the service correctly.

---

```
# v2023.3.4
$ go run main.go service import -c ../docs/sample.yaml
12:22PM INF [apps/v1/deployments] Informer is ready and synced
12:22PM INF [demonstration] No changes detected to fields - skipping update
12:22PM INF [demonstration] All tags already assigned to service.
12:22PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"gitlab.com:test-abc-group/iterm2"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.

12:22PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"github.com:alpha-boneyard/new-nested-opslevel-yml"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.

12:22PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"gitlab.com:test-abc-group/staging-new"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.

# v2024.3.18 (latest)
$ kubectl-opslevel service import -c ../docs/sample.yaml
12:23PM INF [apps/v1/deployments] Informer is ready and synced
12:23PM INF [demonstration] No changes detected to fields - skipping update
12:23PM INF [demonstration] All tags already assigned to service.
12:23PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"github.com:alpha-boneyard/new-nested-opslevel-yml"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.

12:23PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"gitlab.com:test-abc-group/iterm2"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.

12:23PM ERR [demonstration] Failed assigning repository '{"service":null,"repository":{"alias":"gitlab.com:test-abc-group/staging-new"}}'
	REASON: OpsLevel API Errors:
	- 'repository' Repository is already linked to this service at this path.
```

Using config that has:

```
            repositories:
                - '.metadata.annotations | to_entries | map(select(.key | startswith("opslevel.com/repo"))) | map(.value)'
```

**Comment by taimoorgit** [comment] 2024-03-21 18:10
We are going to schedule the fix for this bug for the next release (Mar 29)

**Comment by taimoorgit** [comment] 2024-03-25 16:30
Recording problems with `handleProperties` ([current source](https://github.com/OpsLevel/kubectl-opslevel/blob/7bd2699d17332b54385f40fb3eff19be3c373549/src/common/reconciler.go#L367-L415)) that can cause errors relating to repository handling:

* Repositories are created, but can never be updated, which is confusing because ServiceRepositories are both created and updated.
* ServiceRepositories are looked up using `repository.GetService()` ([opslevel-go source](https://github.com/OpsLevel/opslevel-go/blob/c7fe4a152207f6c2c2428953acc0666cd9cb8692/repository.go#L99-L108)) which will not work without a repository's base directory for some reason.
  * opslevel-go has a way ([source](https://github.com/OpsLevel/opslevel-go/blob/c7fe4a152207f6c2c2428953acc0666cd9cb8692/service.go#L203-L236)) to get ServiceRepositories on a service all at once and without base directory. Using this would cut down on API requests. It also works without a base directory.
  * Our [default config](https://github.com/OpsLevel/kubectl-opslevel/blob/7bd2699d17332b54385f40fb3eff19be3c373549/src/common/configs/config_sample.yaml) doesn't make this clear - since repositories can be created with just the alias, it is assumed that that ServiceRepository would still be able to be updated in some way.

**Comment by taimoorgit** [comment] 2024-03-28 21:18
@lboynton sorry about this - we will not be able to release a fix today or tomorrow but we have a draft PR with a WIP. I will be sure to ping you once we merge the PR and release.

**Comment by taimoorgit** [comment] 2024-04-05 18:54
Closing this issue - was fixed in https://github.com/OpsLevel/kubectl-opslevel/releases/tag/v2024.4.3 (2 days ago) by adding a check to see if a service repository exists and needs an update before attempting to create one.

**Closed as completed by taimoorgit** 2024-04-05 18:54 UTC
